trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Self-hosted agent pool

steps:
  - checkout: self

  - script: |
      docker-compose -f docker-compose.yml pull
      docker-compose -f docker-compose.yml down
      docker-compose -f docker-compose.yml up -d --remove-orphans
    displayName: "Run Docker Compose"

