trigger:
  branches:
    include:
      - main  # or trigger manually or from another pipeline

pool:
  name: Default  # Your self-hosted agent must be in this pool

steps:
  - checkout: self


  - script: |
      docker-compose -f docker-compose.yml pull
      docker-compose -f docker-compose.yml down
      docker-compose -f docker-compose.yml up -d --remove-orphans
    displayName: "Run Docker Compose"

