version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: ayoubaitbarka/backendboutique:latest
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    image: ayoubaitbarka/boutiquefront:latest
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:
